spring:
  application:
    name: bank
  datasource:
    url: jdbc:postgresql://localhost:5432/bank
    username: postgres
    password: postgres
  liquibase:
    change-log: 'classpath:db/changelog/db.changelog-master.xml'
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    template:
      retry:
        enabled: true
        initial-interval: 2s
  web:
    error:
      include-message: ALWAYS
      include-binding-errors: ALWAYS
      include-exception: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-handlers-package: ee.allar.bank.typehandler
  configuration:
    map-underscore-to-camel-case: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html


